# Generated by Django 3.0.8 on 2020-07-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='id',
            new_name='song_id',
        ),
    ]
